server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Srping Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: http://localhost:8084/
          #uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
          filters:
            - name: CustomFilter
            - AddRequestParameter=userid, admin12345
            - AddResponseHeader=first_response, first_response_header
        - id: order-service
          uri: http://localhost:8085/
          #uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CustomFilter
              args:
                baseMessage: Srping Cloud Gateway CustomFilter
                preLogger: true
                postLogger: true
            - AddResponseHeader=second_response, second_response_header
        - id: apihistory-service
          uri: http://localhost:8086/
          #uri: lb://ORDER-SERVICE
          predicates:
            - Path=/apihistory/**
        - id: route1
          uri: http://localhost:8085/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1
      filter:
        request-rate-limiter:
          deny-empty-key: false  # no key resolver needed
  redis:
    host: localhost
    port: 6379
    database: 0

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
         - "gateway"
    gateway:
      enabled: true

logging:
  level:
    root: INFO